(defun words (s)
  (let ((out '()) (cur ""))
    (labels ((flush () (when (> (length cur) 0) (push (string-downcase cur) out) (setf cur ""))))
      (loop for c across s do
        (if (or (alphanumericp c) (char= c #\_))
            (setf cur (concatenate 'string cur (string c)))
            (flush)))
      (flush))
    (nreverse out)))
(let ((file (read-line *standard-input* nil nil))
      (lim-line (read-line *standard-input* nil "20")))
  (when (or (null file) (string= file ""))
    (format t "Usage through Language Project dispatcher: langtools run top-words FILE [LIMIT]~%")
    (quit 2))
  (let ((h (make-hash-table :test 'equal)) (limit (parse-integer lim-line :junk-allowed t)))
    (when (null limit) (setf limit 20))
    (with-open-file (f file)
      (loop for line = (read-line f nil nil) while line do
        (dolist (w (words line)) (incf (gethash w h 0)))))
    (let ((pairs '()))
      (maphash (lambda (k v) (push (cons k v) pairs)) h)
      (setf pairs (sort pairs #'> :key #'cdr))
      (format t "unique_words=~a~%" (hash-table-count h))
      (loop for p in pairs for i from 1 while (<= i limit)
            do (format t "~a~c~a~%" (cdr p) #\Tab (car p))))))
(quit)
