from pathlib import Path
import json,re

TEMPLATES={
'python':('main.py','''#!/usr/bin/env python3\n\ndef main():\n    print("Hello from Language Project")\n\nif __name__ == "__main__":\n    main()\n''','python main.py'),
'javascript':('index.js','''console.log("Hello from Language Project");\n''','node index.js'),
'bash':('main.sh','''#!/data/data/com.termux/files/usr/bin/bash\nset -euo pipefail\necho "Hello from Language Project"\n''','bash main.sh'),
'c':('main.c','''#include <stdio.h>\nint main(void){ puts("Hello from Language Project"); return 0; }\n''','clang -O2 main.c -o app && ./app'),
'cpp':('main.cpp','''#include <iostream>\nint main(){ std::cout << "Hello from Language Project\\n"; }\n''','clang++ -O2 main.cpp -o app && ./app'),
'rust':('main.rs','''fn main() { println!("Hello from Language Project"); }\n''','rustc -O main.rs -o app && ./app'),
'go':('main.go','''package main\nimport "fmt"\nfunc main(){ fmt.Println("Hello from Language Project") }\n''','go run main.go'),
'java':('Main.java','''public class Main { public static void main(String[] args){ System.out.println("Hello from Language Project"); } }\n''','javac Main.java && java Main'),
'kotlin':('Main.kt','''fun main() { println("Hello from Language Project") }\n''','kotlinc Main.kt -include-runtime -d app.jar && java -jar app.jar'),
'lua':('main.lua','''print("Hello from Language Project")\n''','lua main.lua'),
'ruby':('main.rb','''puts "Hello from Language Project"\n''','ruby main.rb'),
'perl':('main.pl','''use strict; use warnings; print "Hello from Language Project\\n";\n''','perl main.pl'),
'php':('main.php','''<?php echo "Hello from Language Project\\n";\n''','php main.php'),
'dart':('main.dart','''void main() { print('Hello from Language Project'); }\n''','dart run main.dart'),
}

def available():return sorted(TEMPLATES)

def create(language,name,directory='.',force=False):
    lang=language.lower();
    if lang not in TEMPLATES:raise ValueError('No starter template for '+language+'. Available: '+', '.join(available()))
    safe=re.sub(r'[^A-Za-z0-9._-]+','-',name).strip('-') or 'language-project-app'
    root=Path(directory).expanduser()/safe
    if root.exists() and any(root.iterdir()) and not force:raise FileExistsError(f'{root} is not empty (use --force to overwrite template files)')
    root.mkdir(parents=True,exist_ok=True)
    filename,source,run=TEMPLATES[lang];p=root/filename
    if p.exists() and not force:raise FileExistsError(str(p))
    p.write_text(source)
    if filename.endswith('.sh'):p.chmod(0o755)
    (root/'README.md').write_text(f'''# {name}\n\nStarter generated by **Language Project**.\n\n## Language\n\n{lang}\n\n## Run in Termux\n\n```bash\n{run}\n```\n''')
    (root/'.gitignore').write_text('app\napp.jar\n*.class\n__pycache__/\n')
    (root/'language-project.json').write_text(json.dumps({'schema':1,'name':name,'language':lang,'entry':filename,'run':run},indent=2)+'\n')
    return {'path':str(root.resolve()),'language':lang,'entry':filename,'run':run}
